version: '3'
services:
  db:
    image: postgres:11.13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  cache:
    image: memcached:1.4.24
    ports:
      - "11211:11211"
  search:
    image: elasticsearch:7.10.1
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
  toxiproxy:
    image: shopify/toxiproxy:2.1.4
    network_mode: "host"
