name: Tests
on:
  pull_request:
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  rails:
    strategy:
      fail-fast: false
      matrix:
        rubygems_version: ['3.3.11', 'latest']
        ruby_version: ['3.1.2']
    name: Rails tests (Ruby ${{ matrix.ruby_version }}, RubyGems ${{ matrix.rubygems_version }})
    runs-on: ubuntu-18.04
    env:
      RUBYGEMS_VERSION: ${{ matrix.rubygems_version }}
      # If we don't supply a CC_TEST_REPORTER_ID simplecov won't output coverage in a way that
      # code climate understands
      CC_TEST_REPORTER_ID: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      # Fail hard when Toxiproxy is not running to ensure all tests (even Toxiproxy optional ones) are passing
      REQUIRE_TOXIPROXY: true
    steps:
    - uses: actions/checkout@v3
    - name: Install and start services
      run: |
        docker-compose up -d
    - name: Wait for ES to boot
      run: |
        timeout 300 bash -c "until curl --silent --output /dev/null http://localhost:9200/_cat/health?h=st; do printf '.'; sleep 5; done; printf '\n'"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: set rubygems version
      run: |
        if [ "$RUBYGEMS_VERSION" != "latest" ]; then
          gem update --system $RUBYGEMS_VERSION;
        else
          gem update --system
        fi
        gem --version
        bundle --version
    - name: Prepare environment
      run: |
        cp config/database.yml.sample config/database.yml
        bundle exec rake db:setup
    - name: Tests
      run: bin/rails test
    - name: archive coverage
      if: matrix.rubygems_version == '3.3.11'
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: |
          coverage
